spring:
  application:
    name: HR-System

  datasource:
    url: jdbc:postgresql://localhost:5432/HR-System
    username: postgres
    password: Jabiyev1!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


